import "../styles/globals.css";
import { Antonio } from "next/font/google";
import { Metadata } from "next";
import Nav from "../components/nav/nav";
import Head from "next/head";

const antonio = Antonio({
    weight: ["400", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    icons: {
        icon: "/favicon.ico?v=1",
        apple: "/apple-touch-icon.png?v=1",
    },
    title: "Kodee",
    description:
        "Kodee er et digitalt byrå som hjelper deg med å gjøre din visjon til en imponerende online tilstedeværelse.",
    keywords: [
        "digital byrå",
        "webdesign tjenester",
        "webutvikling",
        "online tilstedeværelse",
        "visuell identitet",
        "logo design",
        "brukervennlig webdesign",
        "Next.js byrå",
        "Tailwind CSS webdesign",
        "kreativ designløsning",
        "responsive nettsider",
        "SEO optimalisering",
        "kodeutvikling",
        "moderne nettløsninger",
        "webprosjekter",
        "profesjonell nettside",
        "merkevarebygging online",
        "webdesign i Norge",
        "grafisk design tjenester",
        "personlig nettside design",
        "webdesign for bedrifter",
        "branding tjenester",
        "innovativ webdesign",
        "UI/UX design",
        "frontend utvikling",
        "Apollo Client GraphQL",
        "Next.js utvikling",
        "Framer Motion animasjoner",
        "JavaScript nettsider",
        "TypeScript utvikling",
        "brukeropplevelse optimalisering",
        "konverteringsfokusert webdesign",
        "nettside redesign",
        "custom nettsider",
        "mobiloptimaliserte nettsider",
        "interaktiv webdesign",
        "moderne nettutvikling",
        "nettside ytelse optimalisering",
        "web design Norge",
        "nettløsninger for bedrifter",
        "tilpassede nettløsninger",
        "SEO tjenester",
        "digitale strategier",
        "nettside hastighetsoptimalisering",
        "kodebasert design",
        "webdesign tjenester i Oslo",
        "SEO-strategier for små bedrifter",
        "tilpasset nettsideutvikling",
        "nettbutikk design",
        "grafisk design for startups",
        "webutvikling med GraphQL",
        "interaktive nettsider med Framer Motion",
        "digital byrå for småbyer",
        "webdesign tjenester i bygder",
        "webutvikling for småbyer i Norge",
        "online tilstedeværelse for landsbyer",
        "visuell identitet for småbedrifter i Norge",
        "logo design for småbedrifter",
        "brukervennlig webdesign for bygder",
        "tilpassede nettsider for småbyer",
        "SEO optimalisering for bygdesamfunn",
        "responsive nettsider for småbyer",
        "nettsideutvikling for lokale bedrifter",
        "webprosjekter i landsbyer",
        "profesjonell nettside for småsteder",
        "merkevarebygging for små bedrifter",
        "nettside redesign for bygder",
        "webdesign for små bedrifter i Norge",
        "grafisk design tjenester for lokale bedrifter",
        "personlig nettside design for småsteder",
        "SEO-strategier for bygdesamfunn",
        "nettbutikk design for småbyer",
        "mobiloptimaliserte nettsider for småsteder",
        "nettløsninger for små bedrifter i Norge",
        "Next.js utvikling for småbedrifter",
        "frilans webdesign i norske landsbyer",
        "branding tjenester for bygdesamfunn",
        "lokal SEO for småbyer i Norge",
        "digitale strategier for småbyer",
        "webdesign for små bedrifter i bygder",
        "konverteringsfokusert webdesign for småsteder",
        "innovativ webdesign for småbedrifter",
        "UI/UX design for bygder",
        "tilpassede nettløsninger for småsteder",
        "interaktiv webdesign for småbyer",
        "SEO-tjenester for lokale bedrifter i Norge",
        "webdesign i små norske landsbyer",
        "kreativ webutvikling for bygder",
        "nettside for Åndalsnes",
        "nettside for Åfjord",
        "nettside for Åkrehamn",
        "nettside for Alvdal",
        "nettside for Askim",
        "nettside for Aurland",
        "nettside for Ballangen",
        "nettside for Beitostølen",
        "nettside for Bekkjarvik",
        "nettside for Balestrand",
        "nettside for Birkeland",
        "nettside for Bjorli",
        "nettside for Blaker",
        "nettside for Bø i Vesterålen",
        "nettside for Bokn",
        "nettside for Brandbu",
        "nettside for Brønnøysund",
        "nettside for Byglandsfjord",
        "nettside for Bykle",
        "nettside for Dalen",
        "nettside for Dokka",
        "nettside for Drangedal",
        "nettside for Egersund",
        "nettside for Eidsberg",
        "nettside for Eidfjord",
        "nettside for Eidsvoll",
        "nettside for Eikelandsosen",
        "nettside for Evje",
        "nettside for Fagernes",
        "nettside for Farsund",
        "nettside for Finnsnes",
        "nettside for Fiskå",
        "nettside for Fitjar",
        "nettside for Flåm",
        "nettside for Flekkefjord",
        "nettside for Folldal",
        "nettside for Fosen",
        "nettside for Førde",
        "nettside for Førresfjorden",
        "nettside for Fyresdal",
        "nettside for Geilo",
        "nettside for Geiranger",
        "nettside for Gjerstad",
        "nettside for Gol",
        "nettside for Grimstad",
        "nettside for Grong",
        "nettside for Gulen",
        "nettside for Halden",
        "nettside for Halsa",
        "nettside for Harestua",
        "nettside for Hattfjelldal",
        "nettside for Hemsedal",
        "nettside for Hitra",
        "nettside for Hokksund",
        "nettside for Holmestrand",
        "nettside for Hornindal",
        "nettside for Hovden",
        "nettside for Jondal",
        "nettside for Jølster",
        "nettside for Kabelvåg",
        "nettside for Kalvåg",
        "nettside for Karasjok",
        "nettside for Kinsarvik",
        "nettside for Kolvereid",
        "nettside for Koppang",
        "nettside for Kragerø",
        "nettside for Kvinesdal",
        "nettside for Kviteseid",
        "nettside for Lærdal",
        "nettside for Langesund",
        "nettside for Leikanger",
        "nettside for Leknes",
        "nettside for Lillesand",
        "nettside for Lom",
        "nettside for Løten",
        "nettside for Lyngdal",
        "nettside for Mandal",
        "nettside for Mausund",
        "nettside for Melhus",
        "nettside for Midsund",
        "nettside for Moi",
        "nettside for Morgedal",
        "nettside for Nesbyen",
        "nettside for Nissedal",
        "nettside for Nore og Uvdal",
        "nettside for Odda",
        "nettside for Oppdal",
        "nettside for Orkanger",
        "nettside for Rakkestad",
        "nettside for Raufoss",
        "nettside for Risør",
        "nettside for Rjukan",
        "nettside for Rødberg",
        "nettside for Røros",
        "nettside for Røst",
        "nettside for Sand",
        "nettside for Selje",
        "nettside for Sogndal",
        "nettside for Sortland",
        "nettside for Stokmarknes",
        "nettside for Stord",
        "nettside for Stryn",
        "nettside for Suldal",
        "nettside for Sunndalsøra",
        "nettside for Svolvær",
        "nettside for Tinn",
        "nettside for Tysnes",
    ],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="no" className={antonio.className}>
            <Head>
                <script
                    async
                    src={`https://www.googletagmanager.com/gtag/js?id=G-5KK74VTXNX`}
                ></script>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-5KK74VTXNX');
            `,
                    }}
                />
            </Head>
            <body className="bg-brand-dark text-brand-light mx-auto">
                <Nav />
                {children}
            </body>
        </html>
    );
}
